# vault-values.yaml
server:
  affinity: ""
  ha:
    enabled: true
    replicas: 6
    raft: 
      enabled: true   
  image:
    repository: hashicorp/vault-enterprise
    tag: 1.14.0-ent
  enterpriseLicense:
    secretName: vault-ent-license
  extraEnvironmentVars:
    VAULT_CLIENT_TIMEOUT: 300s
ui:
  enabled: true
  publishNotReadyAddresses: true
  activeVaultPodOnly: false
  serviceType: "LoadBalancer"
  serviceNodePort: null
  externalPort: 8200
  targetPort: 8200

